add exit code on verification failure
Wunkolo/qCheck pull request #10
Opened 2023-02-27 22:06 UTC by vgropp

I was in need for an exit code on verification failure to handle it in some script.

What do you think?

2023-02-27 22:41 UTC, Wunkolo commented
This is a good feature, so that a failed check or error can be communicated to outer automation-scripts and such.

2023-03-01 22:01 UTC, vgropp commented
anything you want me to add before merging?

2023-03-01 23:27 UTC, Wunkolo requested changes
Ah I realized my reviews were "pending" and not visible to you this entire time.

2023-03-01 23:27 UTC, Wunkolo commented on source/main.cpp
> +	int ExitCode { EXIT_SUCCESS };
Though the proposed code works, it feels like a bit of a bad pattern to rely on multiple threads to over-write an `int` without any synchronization promises, even if the code can be pretty easily reasoned with. Maybe an `std::atomic<bool> Error{false};` with each thread calling `Error.fetch_or(!Valid)` or `Error.fetch_or(true)` would be better-utilized here to guarantee things are coherent.

2023-03-01 23:27 UTC, Wunkolo commented on source/main.cpp
> +	int ExitCode { EXIT_SUCCESS };
Finding out that `std::atomic<bool>` does not implement `fetch_or`.
Maybe just `std::atomic<std::size_t> Passed{0};` and calling `fetch_add` to count up successful checks and returning `EXIT_SUCCESS`/`EXIT_FAILURE` depending on if _all_ of them passed?

2023-03-02 16:43 UTC, vgropp commented on source/main.cpp
> +	int ExitCode { EXIT_SUCCESS };
I understand your point, will look into it the next days

2023-03-04 12:38 UTC, vgropp commented on source/main.cpp
> +	int ExitCode { EXIT_SUCCESS };
changed to a passed atomic. Really like it more, cause its only adding/changing for passes and comparing those for the exit value

2023-03-04 18:47 UTC, merged